[package]
name = "fragile-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
fragile-common.workspace = true
fragile-hir.workspace = true
inkwell.workspace = true
miette.workspace = true
thiserror.workspace = true
rustc-hash.workspace = true
