[package]
name = "fragile-frontend-go"
version.workspace = true
edition.workspace = true

[dependencies]
fragile-common.workspace = true
fragile-hir.workspace = true
tree-sitter.workspace = true
tree-sitter-go.workspace = true
miette.workspace = true
thiserror.workspace = true
